/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PanierRouteImport } from './routes/panier'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as LivraisonRetoursRouteImport } from './routes/livraison-retours'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CgvRouteImport } from './routes/cgv'
import { Route as BoutiqueRouteImport } from './routes/boutique'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProduitSlugRouteImport } from './routes/produit.$slug'
import { Route as CommandeOrderNumberRouteImport } from './routes/commande.$orderNumber'
import { Route as AuthenticatedCompteRouteImport } from './routes/_authenticated/compte'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedCompteCommandesRouteImport } from './routes/_authenticated/compte.commandes'
import { Route as AuthenticatedCompteAdressesRouteImport } from './routes/_authenticated/compte.adresses'
import { Route as AuthenticatedAdminTemoignagesRouteImport } from './routes/_authenticated/admin/temoignages'
import { Route as AuthenticatedAdminParametresRouteImport } from './routes/_authenticated/admin/parametres'
import { Route as AuthenticatedAdminFacturesRouteImport } from './routes/_authenticated/admin/factures'
import { Route as AuthenticatedAdminClientsRouteImport } from './routes/_authenticated/admin/clients'
import { Route as AuthenticatedAdminCategoriesRouteImport } from './routes/_authenticated/admin/categories'
import { Route as AuthenticatedAdminProduitsIndexRouteImport } from './routes/_authenticated/admin/produits.index'
import { Route as AuthenticatedAdminCommandesIndexRouteImport } from './routes/_authenticated/admin/commandes.index'
import { Route as ApiPublicHooksLowStockAlertRouteImport } from './routes/api/public/hooks/low-stock-alert'
import { Route as AuthenticatedAdminProduitsIdRouteImport } from './routes/_authenticated/admin/produits.$id'
import { Route as AuthenticatedAdminCommandesIdRouteImport } from './routes/_authenticated/admin/commandes.$id'
import { Route as AuthenticatedAdminClientsIdRouteImport } from './routes/_authenticated/admin/clients.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PanierRoute = PanierRouteImport.update({
  id: '/panier',
  path: '/panier',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const LivraisonRetoursRoute = LivraisonRetoursRouteImport.update({
  id: '/livraison-retours',
  path: '/livraison-retours',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CgvRoute = CgvRouteImport.update({
  id: '/cgv',
  path: '/cgv',
  getParentRoute: () => rootRouteImport,
} as any)
const BoutiqueRoute = BoutiqueRouteImport.update({
  id: '/boutique',
  path: '/boutique',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduitSlugRoute = ProduitSlugRouteImport.update({
  id: '/produit/$slug',
  path: '/produit/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandeOrderNumberRoute = CommandeOrderNumberRouteImport.update({
  id: '/commande/$orderNumber',
  path: '/commande/$orderNumber',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCompteRoute = AuthenticatedCompteRouteImport.update({
  id: '/compte',
  path: '/compte',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedCompteCommandesRoute =
  AuthenticatedCompteCommandesRouteImport.update({
    id: '/commandes',
    path: '/commandes',
    getParentRoute: () => AuthenticatedCompteRoute,
  } as any)
const AuthenticatedCompteAdressesRoute =
  AuthenticatedCompteAdressesRouteImport.update({
    id: '/adresses',
    path: '/adresses',
    getParentRoute: () => AuthenticatedCompteRoute,
  } as any)
const AuthenticatedAdminTemoignagesRoute =
  AuthenticatedAdminTemoignagesRouteImport.update({
    id: '/temoignages',
    path: '/temoignages',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminParametresRoute =
  AuthenticatedAdminParametresRouteImport.update({
    id: '/parametres',
    path: '/parametres',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminFacturesRoute =
  AuthenticatedAdminFacturesRouteImport.update({
    id: '/factures',
    path: '/factures',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminClientsRoute =
  AuthenticatedAdminClientsRouteImport.update({
    id: '/clients',
    path: '/clients',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCategoriesRoute =
  AuthenticatedAdminCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminProduitsIndexRoute =
  AuthenticatedAdminProduitsIndexRouteImport.update({
    id: '/produits/',
    path: '/produits/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCommandesIndexRoute =
  AuthenticatedAdminCommandesIndexRouteImport.update({
    id: '/commandes/',
    path: '/commandes/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const ApiPublicHooksLowStockAlertRoute =
  ApiPublicHooksLowStockAlertRouteImport.update({
    id: '/api/public/hooks/low-stock-alert',
    path: '/api/public/hooks/low-stock-alert',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminProduitsIdRoute =
  AuthenticatedAdminProduitsIdRouteImport.update({
    id: '/produits/$id',
    path: '/produits/$id',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCommandesIdRoute =
  AuthenticatedAdminCommandesIdRouteImport.update({
    id: '/commandes/$id',
    path: '/commandes/$id',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminClientsIdRoute =
  AuthenticatedAdminClientsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminClientsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/auth': typeof AuthRoute
  '/boutique': typeof BoutiqueRoute
  '/cgv': typeof CgvRoute
  '/checkout': typeof CheckoutRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/livraison-retours': typeof LivraisonRetoursRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/panier': typeof PanierRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/compte': typeof AuthenticatedCompteRouteWithChildren
  '/commande/$orderNumber': typeof CommandeOrderNumberRoute
  '/produit/$slug': typeof ProduitSlugRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/clients': typeof AuthenticatedAdminClientsRouteWithChildren
  '/admin/factures': typeof AuthenticatedAdminFacturesRoute
  '/admin/parametres': typeof AuthenticatedAdminParametresRoute
  '/admin/temoignages': typeof AuthenticatedAdminTemoignagesRoute
  '/compte/adresses': typeof AuthenticatedCompteAdressesRoute
  '/compte/commandes': typeof AuthenticatedCompteCommandesRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/clients/$id': typeof AuthenticatedAdminClientsIdRoute
  '/admin/commandes/$id': typeof AuthenticatedAdminCommandesIdRoute
  '/admin/produits/$id': typeof AuthenticatedAdminProduitsIdRoute
  '/api/public/hooks/low-stock-alert': typeof ApiPublicHooksLowStockAlertRoute
  '/admin/commandes/': typeof AuthenticatedAdminCommandesIndexRoute
  '/admin/produits/': typeof AuthenticatedAdminProduitsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/auth': typeof AuthRoute
  '/boutique': typeof BoutiqueRoute
  '/cgv': typeof CgvRoute
  '/checkout': typeof CheckoutRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/livraison-retours': typeof LivraisonRetoursRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/panier': typeof PanierRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/compte': typeof AuthenticatedCompteRouteWithChildren
  '/commande/$orderNumber': typeof CommandeOrderNumberRoute
  '/produit/$slug': typeof ProduitSlugRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/clients': typeof AuthenticatedAdminClientsRouteWithChildren
  '/admin/factures': typeof AuthenticatedAdminFacturesRoute
  '/admin/parametres': typeof AuthenticatedAdminParametresRoute
  '/admin/temoignages': typeof AuthenticatedAdminTemoignagesRoute
  '/compte/adresses': typeof AuthenticatedCompteAdressesRoute
  '/compte/commandes': typeof AuthenticatedCompteCommandesRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/clients/$id': typeof AuthenticatedAdminClientsIdRoute
  '/admin/commandes/$id': typeof AuthenticatedAdminCommandesIdRoute
  '/admin/produits/$id': typeof AuthenticatedAdminProduitsIdRoute
  '/api/public/hooks/low-stock-alert': typeof ApiPublicHooksLowStockAlertRoute
  '/admin/commandes': typeof AuthenticatedAdminCommandesIndexRoute
  '/admin/produits': typeof AuthenticatedAdminProduitsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/a-propos': typeof AProposRoute
  '/auth': typeof AuthRoute
  '/boutique': typeof BoutiqueRoute
  '/cgv': typeof CgvRoute
  '/checkout': typeof CheckoutRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/livraison-retours': typeof LivraisonRetoursRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/panier': typeof PanierRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/compte': typeof AuthenticatedCompteRouteWithChildren
  '/commande/$orderNumber': typeof CommandeOrderNumberRoute
  '/produit/$slug': typeof ProduitSlugRoute
  '/_authenticated/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/_authenticated/admin/clients': typeof AuthenticatedAdminClientsRouteWithChildren
  '/_authenticated/admin/factures': typeof AuthenticatedAdminFacturesRoute
  '/_authenticated/admin/parametres': typeof AuthenticatedAdminParametresRoute
  '/_authenticated/admin/temoignages': typeof AuthenticatedAdminTemoignagesRoute
  '/_authenticated/compte/adresses': typeof AuthenticatedCompteAdressesRoute
  '/_authenticated/compte/commandes': typeof AuthenticatedCompteCommandesRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/clients/$id': typeof AuthenticatedAdminClientsIdRoute
  '/_authenticated/admin/commandes/$id': typeof AuthenticatedAdminCommandesIdRoute
  '/_authenticated/admin/produits/$id': typeof AuthenticatedAdminProduitsIdRoute
  '/api/public/hooks/low-stock-alert': typeof ApiPublicHooksLowStockAlertRoute
  '/_authenticated/admin/commandes/': typeof AuthenticatedAdminCommandesIndexRoute
  '/_authenticated/admin/produits/': typeof AuthenticatedAdminProduitsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/auth'
    | '/boutique'
    | '/cgv'
    | '/checkout'
    | '/confidentialite'
    | '/contact'
    | '/cookies'
    | '/livraison-retours'
    | '/mentions-legales'
    | '/panier'
    | '/reset-password'
    | '/sitemap.xml'
    | '/admin'
    | '/compte'
    | '/commande/$orderNumber'
    | '/produit/$slug'
    | '/admin/categories'
    | '/admin/clients'
    | '/admin/factures'
    | '/admin/parametres'
    | '/admin/temoignages'
    | '/compte/adresses'
    | '/compte/commandes'
    | '/admin/'
    | '/admin/clients/$id'
    | '/admin/commandes/$id'
    | '/admin/produits/$id'
    | '/api/public/hooks/low-stock-alert'
    | '/admin/commandes/'
    | '/admin/produits/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/auth'
    | '/boutique'
    | '/cgv'
    | '/checkout'
    | '/confidentialite'
    | '/contact'
    | '/cookies'
    | '/livraison-retours'
    | '/mentions-legales'
    | '/panier'
    | '/reset-password'
    | '/sitemap.xml'
    | '/compte'
    | '/commande/$orderNumber'
    | '/produit/$slug'
    | '/admin/categories'
    | '/admin/clients'
    | '/admin/factures'
    | '/admin/parametres'
    | '/admin/temoignages'
    | '/compte/adresses'
    | '/compte/commandes'
    | '/admin'
    | '/admin/clients/$id'
    | '/admin/commandes/$id'
    | '/admin/produits/$id'
    | '/api/public/hooks/low-stock-alert'
    | '/admin/commandes'
    | '/admin/produits'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/a-propos'
    | '/auth'
    | '/boutique'
    | '/cgv'
    | '/checkout'
    | '/confidentialite'
    | '/contact'
    | '/cookies'
    | '/livraison-retours'
    | '/mentions-legales'
    | '/panier'
    | '/reset-password'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/compte'
    | '/commande/$orderNumber'
    | '/produit/$slug'
    | '/_authenticated/admin/categories'
    | '/_authenticated/admin/clients'
    | '/_authenticated/admin/factures'
    | '/_authenticated/admin/parametres'
    | '/_authenticated/admin/temoignages'
    | '/_authenticated/compte/adresses'
    | '/_authenticated/compte/commandes'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/clients/$id'
    | '/_authenticated/admin/commandes/$id'
    | '/_authenticated/admin/produits/$id'
    | '/api/public/hooks/low-stock-alert'
    | '/_authenticated/admin/commandes/'
    | '/_authenticated/admin/produits/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AProposRoute: typeof AProposRoute
  AuthRoute: typeof AuthRoute
  BoutiqueRoute: typeof BoutiqueRoute
  CgvRoute: typeof CgvRoute
  CheckoutRoute: typeof CheckoutRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  LivraisonRetoursRoute: typeof LivraisonRetoursRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  PanierRoute: typeof PanierRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  CommandeOrderNumberRoute: typeof CommandeOrderNumberRoute
  ProduitSlugRoute: typeof ProduitSlugRoute
  ApiPublicHooksLowStockAlertRoute: typeof ApiPublicHooksLowStockAlertRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panier': {
      id: '/panier'
      path: '/panier'
      fullPath: '/panier'
      preLoaderRoute: typeof PanierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/livraison-retours': {
      id: '/livraison-retours'
      path: '/livraison-retours'
      fullPath: '/livraison-retours'
      preLoaderRoute: typeof LivraisonRetoursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cgv': {
      id: '/cgv'
      path: '/cgv'
      fullPath: '/cgv'
      preLoaderRoute: typeof CgvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boutique': {
      id: '/boutique'
      path: '/boutique'
      fullPath: '/boutique'
      preLoaderRoute: typeof BoutiqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produit/$slug': {
      id: '/produit/$slug'
      path: '/produit/$slug'
      fullPath: '/produit/$slug'
      preLoaderRoute: typeof ProduitSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commande/$orderNumber': {
      id: '/commande/$orderNumber'
      path: '/commande/$orderNumber'
      fullPath: '/commande/$orderNumber'
      preLoaderRoute: typeof CommandeOrderNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/compte': {
      id: '/_authenticated/compte'
      path: '/compte'
      fullPath: '/compte'
      preLoaderRoute: typeof AuthenticatedCompteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/compte/commandes': {
      id: '/_authenticated/compte/commandes'
      path: '/commandes'
      fullPath: '/compte/commandes'
      preLoaderRoute: typeof AuthenticatedCompteCommandesRouteImport
      parentRoute: typeof AuthenticatedCompteRoute
    }
    '/_authenticated/compte/adresses': {
      id: '/_authenticated/compte/adresses'
      path: '/adresses'
      fullPath: '/compte/adresses'
      preLoaderRoute: typeof AuthenticatedCompteAdressesRouteImport
      parentRoute: typeof AuthenticatedCompteRoute
    }
    '/_authenticated/admin/temoignages': {
      id: '/_authenticated/admin/temoignages'
      path: '/temoignages'
      fullPath: '/admin/temoignages'
      preLoaderRoute: typeof AuthenticatedAdminTemoignagesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/parametres': {
      id: '/_authenticated/admin/parametres'
      path: '/parametres'
      fullPath: '/admin/parametres'
      preLoaderRoute: typeof AuthenticatedAdminParametresRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/factures': {
      id: '/_authenticated/admin/factures'
      path: '/factures'
      fullPath: '/admin/factures'
      preLoaderRoute: typeof AuthenticatedAdminFacturesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/clients': {
      id: '/_authenticated/admin/clients'
      path: '/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AuthenticatedAdminClientsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/categories': {
      id: '/_authenticated/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AuthenticatedAdminCategoriesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/produits/': {
      id: '/_authenticated/admin/produits/'
      path: '/produits'
      fullPath: '/admin/produits/'
      preLoaderRoute: typeof AuthenticatedAdminProduitsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/commandes/': {
      id: '/_authenticated/admin/commandes/'
      path: '/commandes'
      fullPath: '/admin/commandes/'
      preLoaderRoute: typeof AuthenticatedAdminCommandesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/api/public/hooks/low-stock-alert': {
      id: '/api/public/hooks/low-stock-alert'
      path: '/api/public/hooks/low-stock-alert'
      fullPath: '/api/public/hooks/low-stock-alert'
      preLoaderRoute: typeof ApiPublicHooksLowStockAlertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/produits/$id': {
      id: '/_authenticated/admin/produits/$id'
      path: '/produits/$id'
      fullPath: '/admin/produits/$id'
      preLoaderRoute: typeof AuthenticatedAdminProduitsIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/commandes/$id': {
      id: '/_authenticated/admin/commandes/$id'
      path: '/commandes/$id'
      fullPath: '/admin/commandes/$id'
      preLoaderRoute: typeof AuthenticatedAdminCommandesIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/clients/$id': {
      id: '/_authenticated/admin/clients/$id'
      path: '/$id'
      fullPath: '/admin/clients/$id'
      preLoaderRoute: typeof AuthenticatedAdminClientsIdRouteImport
      parentRoute: typeof AuthenticatedAdminClientsRoute
    }
  }
}

interface AuthenticatedAdminClientsRouteChildren {
  AuthenticatedAdminClientsIdRoute: typeof AuthenticatedAdminClientsIdRoute
}

const AuthenticatedAdminClientsRouteChildren: AuthenticatedAdminClientsRouteChildren =
  {
    AuthenticatedAdminClientsIdRoute: AuthenticatedAdminClientsIdRoute,
  }

const AuthenticatedAdminClientsRouteWithChildren =
  AuthenticatedAdminClientsRoute._addFileChildren(
    AuthenticatedAdminClientsRouteChildren,
  )

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminCategoriesRoute: typeof AuthenticatedAdminCategoriesRoute
  AuthenticatedAdminClientsRoute: typeof AuthenticatedAdminClientsRouteWithChildren
  AuthenticatedAdminFacturesRoute: typeof AuthenticatedAdminFacturesRoute
  AuthenticatedAdminParametresRoute: typeof AuthenticatedAdminParametresRoute
  AuthenticatedAdminTemoignagesRoute: typeof AuthenticatedAdminTemoignagesRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminCommandesIdRoute: typeof AuthenticatedAdminCommandesIdRoute
  AuthenticatedAdminProduitsIdRoute: typeof AuthenticatedAdminProduitsIdRoute
  AuthenticatedAdminCommandesIndexRoute: typeof AuthenticatedAdminCommandesIndexRoute
  AuthenticatedAdminProduitsIndexRoute: typeof AuthenticatedAdminProduitsIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminCategoriesRoute: AuthenticatedAdminCategoriesRoute,
    AuthenticatedAdminClientsRoute: AuthenticatedAdminClientsRouteWithChildren,
    AuthenticatedAdminFacturesRoute: AuthenticatedAdminFacturesRoute,
    AuthenticatedAdminParametresRoute: AuthenticatedAdminParametresRoute,
    AuthenticatedAdminTemoignagesRoute: AuthenticatedAdminTemoignagesRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
    AuthenticatedAdminCommandesIdRoute: AuthenticatedAdminCommandesIdRoute,
    AuthenticatedAdminProduitsIdRoute: AuthenticatedAdminProduitsIdRoute,
    AuthenticatedAdminCommandesIndexRoute:
      AuthenticatedAdminCommandesIndexRoute,
    AuthenticatedAdminProduitsIndexRoute: AuthenticatedAdminProduitsIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedCompteRouteChildren {
  AuthenticatedCompteAdressesRoute: typeof AuthenticatedCompteAdressesRoute
  AuthenticatedCompteCommandesRoute: typeof AuthenticatedCompteCommandesRoute
}

const AuthenticatedCompteRouteChildren: AuthenticatedCompteRouteChildren = {
  AuthenticatedCompteAdressesRoute: AuthenticatedCompteAdressesRoute,
  AuthenticatedCompteCommandesRoute: AuthenticatedCompteCommandesRoute,
}

const AuthenticatedCompteRouteWithChildren =
  AuthenticatedCompteRoute._addFileChildren(AuthenticatedCompteRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedCompteRoute: typeof AuthenticatedCompteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedCompteRoute: AuthenticatedCompteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AProposRoute: AProposRoute,
  AuthRoute: AuthRoute,
  BoutiqueRoute: BoutiqueRoute,
  CgvRoute: CgvRoute,
  CheckoutRoute: CheckoutRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  LivraisonRetoursRoute: LivraisonRetoursRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  PanierRoute: PanierRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  CommandeOrderNumberRoute: CommandeOrderNumberRoute,
  ProduitSlugRoute: ProduitSlugRoute,
  ApiPublicHooksLowStockAlertRoute: ApiPublicHooksLowStockAlertRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
